# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c60d205fe0908b3c2dec57ee01d280b775f2d9d6393a7a86106a215cd3529df99b3e3760a5e28f74cf1595e566467e812c282320158e3d59921c3e665fb1cf1

test:
  secret_key_base: 9af2dd9ac8ef8c3bef53b0014da583aacba0b76895d5934214fbd7e5227d699473f5b2267048d5f3949bd731f5ea63e332a7897ad55541dd8726a8d081fded47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
